server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
    gateway:
      routes:
        - id: route_buildin
          uri: http://shusheng007.top
          predicates:
            - Header=token,ss007
          filter:
            - PrefixPath=/2022/10/14/redis
        - id: route_vip_service
          uri: https://baidu.com
          predicates:
            - Path=/goods-service/**
            - VipCustomer=vipKey,i-am-vip
          filter:
            - name: AdHandler
              args:
                vipKey: i-am-vip
        #商品服务
        - id: route_goods_service
          uri: lb://goods-service
          predicates:
            - Path=/goods-service/**
          filter:
            - StripPrefix=1
            - name: PrefixPath
              args:
                prefix: /goods
        #物流服务
        - id: route_logistics_service
          uri: lb://logistics-service
          predicates:
            - Path=/logistics-service/**
          filter:
            - StripPrefix=1
            - PrefixPath=/logistics






management:
  endpoints:
    web:
      exposure:
        include: "*"