logging:
  level:
    org.springframework.web: INFO

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      rate: 100

management:
  endpoints:
    web:
      exposure:
#        include: '*'
        include: health,info,metrics,prometheus
